repos:
  - repo: local
    hooks:
      - id: sort_pyproject
        name: sort_pyproject
        entry: toml-sort -i --sort-table-keys --sort-inline-tables
        language: python
        files: ^pyproject\.toml$
        additional_dependencies: ["toml-sort==0.23.1"]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.14
    hooks:
      - id: ruff-format
        types_or: [ python, pyi, jupyter ]
      - id: ruff
        types_or: [ python, pyi, jupyter ]
        args: [ --fix ]
  - repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.338
    hooks:
    - id: pyright
      additional_dependencies: 
        - jax
        - equinox
        - jaxtyping
        - optax
        - numpy
        - scipy
        - matplotlib
        - seaborn
        - optimistix
        - lineax
        - jaxopt
        - healpy
        - astropy
        - tqdm
        - pytest
        - types-PyYAML
        - types-tqdm
        - matplotlib-stubs